apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-exporter-binding
subjects:
- kind: ServiceAccount
  name: prometheus-exporter-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: prometheus-exporter-role
  apiGroup: rbac.authorization.k8s.io

