apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: default
spec:
  selector:
    matchLabels:
      app: kibana
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.0.0
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_SSL_VERIFICATION_MODE
          value: "none"
