apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: default
spec:
  selector:
    app: kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  type: NodePort

