resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"
elasticsearchHosts: "http://elasticsearch-master:9200"

# Optionally, configure Kibana for security (if needed)
# xpack.security.enabled: true
# elasticsearch.password: "your-password"

# Define the Kibana service type
service:
  type: LoadBalancer
