apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch-test
  namespace: default
spec:
  containers:
  - name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    env:
    - name: discovery.type
      value: single-node
    - name: xpack.security.enrollment.enabled
      value: "true"
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "4Gi"
        cpu: "500m"
    ports:
    - containerPort: 9200
      name: http
    - containerPort: 9300
      name: transport

